### ISSUE TITLE
invalid syntax

### ISSUE THREAD

**Issue by ghost** [btimofeev/lazy_ips#6]
Just built and installed the current HEAD and I get this error running the CLI version:
```
$ lazy-ips-cli
Traceback (most recent call last):
  File "/usr/local/bin/lazy-ips-cli", line 11, in <module>
    load_entry_point('lazy-ips==20191208', 'console_scripts', 'lazy-ips-cli')()
  File "/usr/local/lib/python3.5/dist-packages/pkg_resources/__init__.py", line 480, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/local/lib/python3.5/dist-packages/pkg_resources/__init__.py", line 2693, in load_entry_point
    return ep.load()
  File "/usr/local/lib/python3.5/dist-packages/pkg_resources/__init__.py", line 2324, in load
    return self.resolve()
  File "/usr/local/lib/python3.5/dist-packages/pkg_resources/__init__.py", line 2330, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 954, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 896, in _find_spec
  File "<frozen importlib._bootstrap_external>", line 1139, in find_spec
  File "<frozen importlib._bootstrap_external>", line 1115, in _get_spec
  File "<frozen importlib._bootstrap_external>", line 1096, in _legacy_get_spec
  File "<frozen importlib._bootstrap>", line 444, in spec_from_loader
  File "<frozen importlib._bootstrap_external>", line 533, in spec_from_file_location
  File "/usr/local/lib/python3.5/dist-packages/lazy_ips-20191208-py3.5.egg/lazy_ips/cli.py", line 17
    print(f"Error opening {args.image_file}: {err}")
                                                  ^
SyntaxError: invalid syntax
```

Any ideas?

**Comment by btimofeev** [comment]
Thanks for reporting the error.

f-strings only work on Python version 3.6 and higher. You can fix this by installing the https://pypi.org/project/future-fstrings/ library and adding a line to the top of the file

 `# -*- coding: future_fstrings -*-`

I will fix this in the next few days.

**Comment by btimofeev** [comment]
@bparker06 try updating, it should work now

**Comment by ghost** [comment]
all good, thanks!
